/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableModel;

/*
 * @author Nicolas Herrera <herrera.nicolas@correounivalle.edu.co>
 * @author Samuel Galindo Cuevas <samuel.galindo@correounivalle.edu.co>
 */

public class VistaPronostico extends javax.swing.JFrame {

    /**
     * Creates new form VistaPronostico
     */
    public VistaPronostico()
    {
        initComponents();

        jtHistoricoVentas.addMouseListener(new TablaHistoricoVentasListener());
    }

    public void pantallaCompleta()
    {
        this.setVisible(true);
        this.setExtendedState(this.getExtendedState() | this.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jpSuperior = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jpCentral = new javax.swing.JPanel();
        jpCantidadVenta = new javax.swing.JPanel();
        lblDatosVenta = new javax.swing.JLabel();
        lblCantidadVentas = new javax.swing.JLabel();
        txtCantidadVentas = new javax.swing.JTextField();
        jpAñosPronosticar = new javax.swing.JPanel();
        lblAñosPronosticar = new javax.swing.JLabel();
        lblCantidadAños = new javax.swing.JLabel();
        txtCantidadAños = new javax.swing.JTextField();
        jpControles = new javax.swing.JPanel();
        lblControles = new javax.swing.JLabel();
        btnAgregarAño = new javax.swing.JButton();
        btnBorrarAño = new javax.swing.JButton();
        btnModificarAño = new javax.swing.JButton();
        btnNuevoPronostico = new javax.swing.JButton();
        jpHistorialVentas = new javax.swing.JPanel();
        jspHistoricoVentas = new javax.swing.JScrollPane();
        jtHistoricoVentas = new javax.swing.JTable();
        lblHistoricoVentas = new javax.swing.JLabel();
        lblTotalVariacion = new javax.swing.JLabel();
        txtTotalVariacion = new javax.swing.JTextField();
        txtAño = new javax.swing.JTextField();
        jpPronosticosVentas = new javax.swing.JPanel();
        lblPronosticoVentas = new javax.swing.JLabel();
        lblPromedioVariacion = new javax.swing.JLabel();
        txtPromedioVariacion = new javax.swing.JTextField();
        jspPronosticoVentas = new javax.swing.JScrollPane();
        jtPronosticoVenta = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PRONOSTICO VENTAS");
        setResizable(false);

        jpSuperior.setBackground(new java.awt.Color(109, 152, 134));
        jpSuperior.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 20));

        lblTitulo.setFont(new java.awt.Font("Montserrat", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("PRONOSTICO DE VENTAS");
        jpSuperior.add(lblTitulo);

        getContentPane().add(jpSuperior, java.awt.BorderLayout.PAGE_START);

        jpCentral.setBackground(new java.awt.Color(248, 244, 234));
        jpCentral.setLayout(new java.awt.GridBagLayout());

        jpCantidadVenta.setBackground(new java.awt.Color(248, 244, 234));
        jpCantidadVenta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(225, 215, 198), 5, true));
        jpCantidadVenta.setToolTipText("");
        jpCantidadVenta.setLayout(new java.awt.GridBagLayout());

        lblDatosVenta.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lblDatosVenta.setForeground(new java.awt.Color(51, 51, 51));
        lblDatosVenta.setText("DATOS VENTA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 15);
        jpCantidadVenta.add(lblDatosVenta, gridBagConstraints);

        lblCantidadVentas.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        lblCantidadVentas.setForeground(new java.awt.Color(51, 51, 51));
        lblCantidadVentas.setText("CANTIDAD VENTAS:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 15);
        jpCantidadVenta.add(lblCantidadVentas, gridBagConstraints);

        txtCantidadVentas.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        txtCantidadVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadVentasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 15, 15);
        jpCantidadVenta.add(txtCantidadVentas, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        jpCentral.add(jpCantidadVenta, gridBagConstraints);

        jpAñosPronosticar.setBackground(new java.awt.Color(248, 244, 234));
        jpAñosPronosticar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(225, 215, 198), 5, true));
        jpAñosPronosticar.setLayout(new java.awt.GridBagLayout());

        lblAñosPronosticar.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lblAñosPronosticar.setForeground(new java.awt.Color(51, 51, 51));
        lblAñosPronosticar.setText("AÑOS A PRONOSTICAR");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 15);
        jpAñosPronosticar.add(lblAñosPronosticar, gridBagConstraints);

        lblCantidadAños.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        lblCantidadAños.setForeground(new java.awt.Color(51, 51, 51));
        lblCantidadAños.setText("CANTIDAD:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 15);
        jpAñosPronosticar.add(lblCantidadAños, gridBagConstraints);

        txtCantidadAños.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 15, 15);
        jpAñosPronosticar.add(txtCantidadAños, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        jpCentral.add(jpAñosPronosticar, gridBagConstraints);

        jpControles.setBackground(new java.awt.Color(248, 244, 234));
        jpControles.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(225, 215, 198), 5, true));
        jpControles.setLayout(new java.awt.GridBagLayout());

        lblControles.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lblControles.setForeground(new java.awt.Color(51, 51, 51));
        lblControles.setText("CONTROLES");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 15);
        jpControles.add(lblControles, gridBagConstraints);

        btnAgregarAño.setBackground(new java.awt.Color(248, 248, 248));
        btnAgregarAño.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        btnAgregarAño.setText("AGREGAR AÑO");
        btnAgregarAño.setFocusPainted(false);
        btnAgregarAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAñoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 5, 15);
        jpControles.add(btnAgregarAño, gridBagConstraints);

        btnBorrarAño.setBackground(new java.awt.Color(248, 248, 248));
        btnBorrarAño.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        btnBorrarAño.setText("BORRAR AÑO");
        btnBorrarAño.setFocusPainted(false);
        btnBorrarAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarAñoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 15);
        jpControles.add(btnBorrarAño, gridBagConstraints);

        btnModificarAño.setBackground(new java.awt.Color(248, 248, 248));
        btnModificarAño.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        btnModificarAño.setText("MODIFICAR AÑO");
        btnModificarAño.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 15);
        jpControles.add(btnModificarAño, gridBagConstraints);

        btnNuevoPronostico.setBackground(new java.awt.Color(248, 248, 248));
        btnNuevoPronostico.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        btnNuevoPronostico.setText("NUEVO PRONOSTICO");
        btnNuevoPronostico.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 15, 15);
        jpControles.add(btnNuevoPronostico, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        jpCentral.add(jpControles, gridBagConstraints);

        jpHistorialVentas.setBackground(new java.awt.Color(248, 244, 234));
        jpHistorialVentas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(225, 215, 198), 5, true));
        jpHistorialVentas.setLayout(new java.awt.GridBagLayout());

        jspHistoricoVentas.getViewport().setBackground(Color.white);

        jtHistoricoVentas.getTableHeader().setBackground(new Color(248,248,248));
        jtHistoricoVentas.getTableHeader().setFont(new java.awt.Font("Montserrat Medium", 0, 12));
        jtHistoricoVentas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtHistoricoVentas.setDefaultEditor(Object.class, null);
        jtHistoricoVentas.getTableHeader().setResizingAllowed(false);
        jtHistoricoVentas.getTableHeader().setReorderingAllowed(false);
        jtHistoricoVentas.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jtHistoricoVentas.setForeground(new java.awt.Color(51, 51, 51));
        jtHistoricoVentas.setModel(new javax.swing.table.DefaultTableModel(
                null,
                new String []
                        {
                                "AÑO", "CANTIDAD VENTAS", "VARIACION VENTA", "PORCENTAJE VARIACION"
                        }
        ));
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( SwingConstants.CENTER );
        jtHistoricoVentas.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        jtHistoricoVentas.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        jtHistoricoVentas.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        jtHistoricoVentas.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
        jtHistoricoVentas.setFocusable(false);
        jtHistoricoVentas.setMinimumSize(null);
        jtHistoricoVentas.setPreferredSize(null);
        jspHistoricoVentas.setViewportView(jtHistoricoVentas);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 400;
        gridBagConstraints.ipady = 150;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 15);
        jpHistorialVentas.add(jspHistoricoVentas, gridBagConstraints);

        lblHistoricoVentas.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lblHistoricoVentas.setForeground(new java.awt.Color(51, 51, 51));
        lblHistoricoVentas.setText("HISTORICO VENTAS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jpHistorialVentas.add(lblHistoricoVentas, gridBagConstraints);

        lblTotalVariacion.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        lblTotalVariacion.setText("TOTAL PORCENTAJE DE VARIACION:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jpHistorialVentas.add(lblTotalVariacion, gridBagConstraints);

        txtTotalVariacion.setEditable(false);
        txtTotalVariacion.setBackground(new java.awt.Color(255, 255, 255));
        txtTotalVariacion.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        txtTotalVariacion.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        jpHistorialVentas.add(txtTotalVariacion, gridBagConstraints);

        txtAño.setEditable(false);
        txtAño.setText("0");
        txtAño.setEnabled(false);
        txtAño.setFocusable(false);
        txtAño.setVisible(false);
        jpHistorialVentas.add(txtAño, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jpCentral.add(jpHistorialVentas, gridBagConstraints);

        jpPronosticosVentas.setBackground(new java.awt.Color(248, 244, 234));
        jpPronosticosVentas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(225, 215, 198), 5, true));
        jpPronosticosVentas.setLayout(new java.awt.GridBagLayout());

        lblPronosticoVentas.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        lblPronosticoVentas.setForeground(new java.awt.Color(51, 51, 51));
        lblPronosticoVentas.setText("PRONOSTICO VENTAS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jpPronosticosVentas.add(lblPronosticoVentas, gridBagConstraints);

        lblPromedioVariacion.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        lblPromedioVariacion.setForeground(new java.awt.Color(51, 51, 51));
        lblPromedioVariacion.setText("PROMEDIO DE VARIACION:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jpPronosticosVentas.add(lblPromedioVariacion, gridBagConstraints);

        txtPromedioVariacion.setEditable(false);
        txtPromedioVariacion.setBackground(new java.awt.Color(255, 255, 255));
        txtPromedioVariacion.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        txtPromedioVariacion.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        jpPronosticosVentas.add(txtPromedioVariacion, gridBagConstraints);

        jspPronosticoVentas.getViewport().setBackground(Color.white);
        jspPronosticoVentas.setBorder(null);
        jspPronosticoVentas.setMaximumSize(null);

        jtPronosticoVenta.getTableHeader().setBackground(new Color(248,248,248));
        jtPronosticoVenta.getTableHeader().setFont(new java.awt.Font("Montserrat Medium", 0, 12));
        jtPronosticoVenta.setDefaultEditor(Object.class, null);
        jtPronosticoVenta.setEnabled(false);
        jtPronosticoVenta.getTableHeader().setResizingAllowed(false);
        jtPronosticoVenta.getTableHeader().setReorderingAllowed(false);
        jtPronosticoVenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(225, 215, 198)));
        jtPronosticoVenta.setModel(new javax.swing.table.DefaultTableModel(
                null,
                new String []
                        {
                                "AÑO", "PRONOSTICO VENTAS"
                        }
        ));
        jtPronosticoVenta.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        jtPronosticoVenta.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        jtPronosticoVenta.setOpaque(false);
        jspPronosticoVentas.setViewportView(jtPronosticoVenta);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 400;
        gridBagConstraints.ipady = 150;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 15);
        jpPronosticosVentas.add(jspPronosticoVentas, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jpCentral.add(jpPronosticosVentas, gridBagConstraints);

        getContentPane().add(jpCentral, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>

    private void btnAgregarAñoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btnBorrarAñoActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtCantidadVentasActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    //==========|ActionListeners|==========//
    public void addBtnAgregarAñoListener(ActionListener listenControles)
    {
        btnAgregarAño.addActionListener(listenControles);
    }

    public void addBtnBorrarAñoListener(ActionListener listenControles)
    {
        btnBorrarAño.addActionListener(listenControles);
    }

    public void addBtnModificarAñoListener(ActionListener listenControles)
    {
        btnModificarAño.addActionListener(listenControles);
    }

    public void addBtnNuevoPronosticoListener(ActionListener listenControles)
    {
        btnNuevoPronostico.addActionListener(listenControles);
    }

    //==========|MouseListener|==========//
    class TablaHistoricoVentasListener extends MouseAdapter
    {
        @Override
        public void mouseClicked(MouseEvent e)
        {
            JTable tabla = (JTable)e.getSource();
            int fila = tabla.getSelectedRow();
            if(fila == -1)
            {
                txtAño.setText("0");
                txtCantidadVentas.setText("");
            }
            else
            {
                txtAño.setText(String.valueOf(tabla.getValueAt(fila , 0)));
                txtCantidadVentas.setText(String.valueOf(tabla.getValueAt(fila , 1)));
            }

        }
    }

    //==========|Tablas|==========//
    public TableModel getTableModelHistoricoVentas()
    {
        return jtHistoricoVentas.getModel();
    }

    public int getFilaSeleccionadaVentas()
    {
        return jtHistoricoVentas.getSelectedRow();
    }

    public void deseleccionarFilaTablaVentas()
    {
        jtHistoricoVentas.getSelectionModel().clearSelection();
    }

    public TableModel getTableModelPronostico()
    {
        return jtPronosticoVenta.getModel();
    }

    //==========|Gets|==========//
    public String getCantidadVentas()
    {
        return txtCantidadVentas.getText();
    }

    public String getCantidadAños()
    {
        return txtCantidadAños.getText();
    }

    public String getAño()
    {
        return txtAño.getText();
    }

    public String getPorcentajeVarTotal()
    {
        return txtTotalVariacion.getText();
    }

    public String getPromedioVariacion()
    {
        return txtPromedioVariacion.getText();
    }

    //==========|Sets|==========//
    public void setCantidadVentas(String txt)
    {
        txtCantidadVentas.setText(txt);
    }

    public void setCantidadAños(String txt)
    {
        txtCantidadAños.setText(txt);
    }

    public void setAño(String txt)
    {
        txtAño.setText(txt);
    }

    public void setTotalVariacion(String txt)
    {
        txtTotalVariacion.setText(txt);
    }

    public void setPromedioVariacion(String txt)
    {
        txtPromedioVariacion.setText(txt);
    }

    //==========|Mensajes|==========//
    public void mostrarMensajeError(String txt)
    {
        JOptionPane.showMessageDialog(this, txt, "", JOptionPane.ERROR_MESSAGE);
    }


    // Variables declaration - do not modify
    private javax.swing.JButton btnAgregarAño;
    private javax.swing.JButton btnBorrarAño;
    private javax.swing.JButton btnModificarAño;
    private javax.swing.JButton btnNuevoPronostico;
    private javax.swing.JPanel jpAñosPronosticar;
    private javax.swing.JPanel jpCantidadVenta;
    private javax.swing.JPanel jpCentral;
    private javax.swing.JPanel jpControles;
    private javax.swing.JPanel jpHistorialVentas;
    private javax.swing.JPanel jpPronosticosVentas;
    private javax.swing.JPanel jpSuperior;
    private javax.swing.JScrollPane jspHistoricoVentas;
    private javax.swing.JScrollPane jspPronosticoVentas;
    private javax.swing.JTable jtHistoricoVentas;
    private javax.swing.JTable jtPronosticoVenta;
    private javax.swing.JLabel lblAñosPronosticar;
    private javax.swing.JLabel lblCantidadAños;
    private javax.swing.JLabel lblCantidadVentas;
    private javax.swing.JLabel lblControles;
    private javax.swing.JLabel lblDatosVenta;
    private javax.swing.JLabel lblHistoricoVentas;
    private javax.swing.JLabel lblPromedioVariacion;
    private javax.swing.JLabel lblPronosticoVentas;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotalVariacion;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtCantidadAños;
    private javax.swing.JTextField txtCantidadVentas;
    private javax.swing.JTextField txtPromedioVariacion;
    private javax.swing.JTextField txtTotalVariacion;
    // End of variables declaration
}
